title: jstoetz
author:
  name: Jake Stoetzner
  email: Jake.stoetzner@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Adventures in R programming and data science for stocks, ETFs and options, as well as commercial real estate and sports gambling.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jstoetz
    github:  jstoetz
    rss: rss
    facebook: jstoetz
    telegram: jstoetz

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
#- blog.html
#- code.md
- about.md
- rbasics.html
- resources.html
- rstyleguide.html

# Build settings
theme: minima

# Default Links
permalink: pretty

# How many blog posts to show
paginate: 5

collections:
  resources:
    output: true
    permalink: /:collection/:name
  rbasics:
    output: true
    permalink: /:collection/:name
  rstyleguide:
    output: true
    permalink: /:collection/name

# production_url : http://jstoetz.github.io/
# BASE_PATH : https://jstoetz.github.io/

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
