title: jstoetz
author:
  name: Jake Stoetzner
  email: Jake.stoetzner@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Adventures in R programming and data science for stocks, ETFs and options, as well as commercial real estate and sports gambling.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jstoetz
    github:  jstoetz
    rss: rss
    # dribbble: jekyll
    facebook: jstoetz
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    telegram: jstoetz
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- blog.html
- about.md

# Build settings
theme: minima

# Default Links
permalink: pretty

# How many blog posts to show
paginate: 5

#
collections:
    r_basics:
      output: true
      permalink: /:collection/:name

# production_url : http://jstoetz.github.io/
# BASE_PATH : https://jstoetz.github.io/

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
